### PR TITLE
ESP-IDF component

### PR DESCRIPTION
**Pull request by VedantParanjape**
Converted to esp-idf component, tested with a app, works

### CODE REVIEW

**Comment by nopnop2002** [comment]
I updated CMakeLists.txt 4 days ago.
Please check the latest version.

**Comment by VedantParanjape** [comment]
Updating the CmakeLists doesn't make this a component.

**Comment by nopnop2002** [comment]
Can you please explain the benefits of your PR again? ?

**Comment by nopnop2002** [comment]
If you want to expose it as a component, I suggest the following:


1. Your repository and my repository exist independently.

2. Your repository renames esp-idf-ssd1306 to esp-idf-ssd1306-component.

3. The README for my repository states that your repository is available as a component.


Please consider.

**Comment by VedantParanjape** [comment]
Yup, Seems good. I'll do so. 

Regards.

**Pull request closed without merging**
